# Generated by Django 4.2.5 on 2024-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recent_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default=1, upload_to='category_images'),
            preserve_default=False,
        ),
    ]
