# Generated by Django 5.0.2 on 2024-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recent_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
